import { MATERIALS } from "./materials";

export const TEMPLATES = {
  column: {
    name: "Simple Concrete Column",
    description: "A tall vertical pillar of Concrete demonstrating basic vertical load path. Stable up to 37 blocks.",
    cubes: [
      { x: 0, y: 0.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 1.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 2.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 3.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 4.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 5.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 6.5, z: 0, material: MATERIALS.CONCRETE }
    ]
  },
  cantilever: {
    name: "Cantilever Beam",
    description: "A Concrete pillar supporting a Steel arm extending horizontally. Wood or concrete arms would snap, but Steel is strong enough.",
    cubes: [
      // Concrete Pillar
      { x: -3, y: 0.5, z: 0, material: MATERIALS.CONCRETE },
      { x: -3, y: 1.5, z: 0, material: MATERIALS.CONCRETE },
      { x: -3, y: 2.5, z: 0, material: MATERIALS.CONCRETE },
      { x: -3, y: 3.5, z: 0, material: MATERIALS.CONCRETE },
      { x: -3, y: 4.5, z: 0, material: MATERIALS.CONCRETE },
      // Horizontal Steel cantilever
      { x: -2, y: 4.5, z: 0, material: MATERIALS.STEEL },
      { x: -1, y: 4.5, z: 0, material: MATERIALS.STEEL },
      { x: 0, y: 4.5, z: 0, material: MATERIALS.STEEL },
      { x: 1, y: 4.5, z: 0, material: MATERIALS.STEEL },
      { x: 2, y: 4.5, z: 0, material: MATERIALS.STEEL }
    ]
  },
  arch: {
    name: "Concrete Arch Bridge",
    description: "A compression-only arch bridge. Concrete performs exceptionally well here because gravity loads are directed downwards and inwards, avoiding shear failure.",
    cubes: [
      { x: -4, y: 0.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 4, y: 0.5, z: 0, material: MATERIALS.CONCRETE },
      
      { x: -3, y: 1.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 3, y: 1.5, z: 0, material: MATERIALS.CONCRETE },
      
      { x: -2, y: 2.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 2, y: 2.5, z: 0, material: MATERIALS.CONCRETE },
      
      { x: -1, y: 3.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.CONCRETE },
      { x: 0, y: 3.5, z: 0, material: MATERIALS.CONCRETE }
    ]
  },
  tower: {
    name: "Aluminum Truss Tower",
    description: "A tall structure made of lightweight Aluminum to minimize self-weight while maximizing height. Excellent for wind/shear loads.",
    cubes: [
      // Base
      { x: -1, y: 0.5, z: -1, material: MATERIALS.ALUMINUM },
      { x: 1, y: 0.5, z: -1, material: MATERIALS.ALUMINUM },
      { x: -1, y: 0.5, z: 1, material: MATERIALS.ALUMINUM },
      { x: 1, y: 0.5, z: 1, material: MATERIALS.ALUMINUM },
      // Tier 1
      { x: -1, y: 1.5, z: -1, material: MATERIALS.ALUMINUM },
      { x: 1, y: 1.5, z: -1, material: MATERIALS.ALUMINUM },
      { x: -1, y: 1.5, z: 1, material: MATERIALS.ALUMINUM },
      { x: 1, y: 1.5, z: 1, material: MATERIALS.ALUMINUM },
      { x: 0, y: 1.5, z: 0, material: MATERIALS.ALUMINUM },
      // Tier 2
      { x: 0, y: 2.5, z: 0, material: MATERIALS.ALUMINUM },
      { x: 0, y: 3.5, z: 0, material: MATERIALS.ALUMINUM },
      { x: 0, y: 4.5, z: 0, material: MATERIALS.ALUMINUM },
      // Platform
      { x: -1, y: 5.5, z: 0, material: MATERIALS.ALUMINUM },
      { x: 1, y: 5.5, z: 0, material: MATERIALS.ALUMINUM },
      { x: 0, y: 5.5, z: -1, material: MATERIALS.ALUMINUM },
      { x: 0, y: 5.5, z: 1, material: MATERIALS.ALUMINUM },
      { x: 0, y: 5.5, z: 0, material: MATERIALS.ALUMINUM },
      // Tip
      { x: 0, y: 6.5, z: 0, material: MATERIALS.ALUMINUM },
      { x: 0, y: 7.5, z: 0, material: MATERIALS.ALUMINUM }
    ]
  },
  pavilion: {
    name: "Wood Pavilion",
    description: "A small shelter made of Wood. Shows how wood is a cost-effective material for small spans.",
    cubes: [
      // Pillars
      { x: -2, y: 0.5, z: -2, material: MATERIALS.WOOD },
      { x: -2, y: 1.5, z: -2, material: MATERIALS.WOOD },
      { x: 2, y: 0.5, z: -2, material: MATERIALS.WOOD },
      { x: 2, y: 1.5, z: -2, material: MATERIALS.WOOD },
      { x: -2, y: 0.5, z: 2, material: MATERIALS.WOOD },
      { x: -2, y: 1.5, z: 2, material: MATERIALS.WOOD },
      { x: 2, y: 0.5, z: 2, material: MATERIALS.WOOD },
      { x: 2, y: 1.5, z: 2, material: MATERIALS.WOOD },
      // Roof Ring
      { x: -2, y: 2.5, z: -2, material: MATERIALS.WOOD },
      { x: -1, y: 2.5, z: -2, material: MATERIALS.WOOD },
      { x: 0, y: 2.5, z: -2, material: MATERIALS.WOOD },
      { x: 1, y: 2.5, z: -2, material: MATERIALS.WOOD },
      { x: 2, y: 2.5, z: -2, material: MATERIALS.WOOD },
      
      { x: -2, y: 2.5, z: 2, material: MATERIALS.WOOD },
      { x: -1, y: 2.5, z: 2, material: MATERIALS.WOOD },
      { x: 0, y: 2.5, z: 2, material: MATERIALS.WOOD },
      { x: 1, y: 2.5, z: 2, material: MATERIALS.WOOD },
      { x: 2, y: 2.5, z: 2, material: MATERIALS.WOOD },

      { x: -2, y: 2.5, z: -1, material: MATERIALS.WOOD },
      { x: -2, y: 2.5, z: 0, material: MATERIALS.WOOD },
      { x: -2, y: 2.5, z: 1, material: MATERIALS.WOOD },
      
      { x: 2, y: 2.5, z: -1, material: MATERIALS.WOOD },
      { x: 2, y: 2.5, z: 0, material: MATERIALS.WOOD },
      { x: 2, y: 2.5, z: 1, material: MATERIALS.WOOD },
      
      // Roof Center
      { x: 0, y: 3.5, z: 0, material: MATERIALS.WOOD },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.WOOD },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.WOOD },
      { x: 0, y: 3.5, z: -1, material: MATERIALS.WOOD },
      { x: 0, y: 3.5, z: 1, material: MATERIALS.WOOD }
    ]
  },
  modern_house: {
    name: "Modern Villa",
    description: "A premium 2-story Modern Villa featuring a marble & tile open-floor plan, steel structural columns, large panoramic glass windows, and interactive doors.",
    cubes: [
      { x: -3, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 4, material: MATERIALS.CONCRETE, shape: "stair", rotationY: 0 },
      { x: -3, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 1.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 1.5, z: 3, material: MATERIALS.WOOD, shape: "door", rotationY: 0 },
      { x: 1, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 1.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 2.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 2.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 1.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 1.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 2.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 2.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 0, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 3, y: 1.5, z: -2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: -2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: -1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: -1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 0, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: -3, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 1.5, z: 0, material: MATERIALS.CARPET, shape: "sofa", rotationY: 1 },
      { x: 0, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "table" },
      { x: -1, y: 1.5, z: 0, material: MATERIALS.STEEL, shape: "tv", rotationY: 3 },
      { x: -2, y: 1.5, z: 2, material: MATERIALS.CARPET, shape: "bed", rotationY: 2 },
      { x: 2, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "kitchen_cabinet", rotationY: 0 },
      { x: 1, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "fridge", rotationY: 0 },
      { x: 0, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "sink", rotationY: 0 },
      { x: -2, y: 1.5, z: -2, material: MATERIALS.MARBLE, shape: "bathtub", rotationY: 1 },
      { x: -1, y: 1.5, z: -2, material: MATERIALS.MARBLE, shape: "toilet", rotationY: 0 },
      { x: 0, y: 1.5, z: 2, material: MATERIALS.STEEL, shape: "lamp" },
      { x: -2.9, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "painting", rotationY: 3 }
    ]
  },
  old_house: {
    name: "Brick Cottage",
    description: "An old-fashioned brick house with wooden flooring, glass windows, a brick fireplace chimney, and a slanted/pitched wooden roof.",
    cubes: [
      { x: -2, y: 0.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 0.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 0.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 0.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 0.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 0.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 0.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 0.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 0.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 0.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 0, y: 0.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 0, y: 0.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 0, y: 0.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: 0, y: 0.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 0, y: 0.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 1, y: 0.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 1, y: 0.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 1, y: 0.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: 1, y: 0.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 1, y: 0.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 2, y: 0.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: 2, y: 0.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 2, y: 0.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: 2, y: 0.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: 2, y: 0.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 1.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 1.5, z: 1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 1.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -1, y: 1.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -1, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 0, y: 1.5, z: -2, material: MATERIALS.WOOD, shape: "door", rotationY: 0 },
      { x: 0, y: 1.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 1, y: 1.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 1, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 1.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 1.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 1.5, z: 1, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 1.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 2.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 2.5, z: 0, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 2.5, z: 1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 2.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -1, y: 2.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -1, y: 2.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 0, y: 2.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 0, y: 2.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 1, y: 2.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 1, y: 2.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 2.5, z: -2, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 2.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 2.5, z: 0, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 2.5, z: 1, material: MATERIALS.BRICK, shape: "cube" },
      { x: 2, y: 2.5, z: 2, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 0.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 1.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 2.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 3.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 4.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 5.5, z: -1, material: MATERIALS.BRICK, shape: "cube" },
      { x: -2, y: 3.5, z: -2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: -1, y: 3.5, z: -2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: 2, y: 3.5, z: -2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 1, y: 3.5, z: -2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 0, y: 4.5, z: -2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 3.5, z: -1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: -1, y: 3.5, z: -1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: 2, y: 3.5, z: -1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 1, y: 3.5, z: -1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 0, y: 4.5, z: -1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 3.5, z: 0, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: 2, y: 3.5, z: 0, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 0, y: 4.5, z: 0, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 3.5, z: 1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: -1, y: 3.5, z: 1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: 2, y: 3.5, z: 1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 1, y: 3.5, z: 1, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 0, y: 4.5, z: 1, material: MATERIALS.WOOD, shape: "slab" },
      { x: -2, y: 3.5, z: 2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: -1, y: 3.5, z: 2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 3 },
      { x: 2, y: 3.5, z: 2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 1, y: 3.5, z: 2, material: MATERIALS.WOOD, shape: "ramp", rotationY: 1 },
      { x: 0, y: 4.5, z: 2, material: MATERIALS.WOOD, shape: "slab" },
      { x: -1, y: 1.5, z: 1, material: MATERIALS.CARPET, shape: "bed", rotationY: 2 },
      { x: 1, y: 1.5, z: -1, material: MATERIALS.WOOD, shape: "table" },
      { x: 1, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "chair", rotationY: 2 },
      { x: -1, y: 1.5, z: -1, material: MATERIALS.STEEL, shape: "lamp" },
      { x: 1, y: 1.5, z: -2, material: MATERIALS.WOOD, shape: "kitchen_cabinet" },
      { x: -1, y: 1.5, z: -2, material: MATERIALS.WOOD, shape: "kitchen_cabinet" },
      { x: 0, y: 2.5, z: 1, material: MATERIALS.WOOD, shape: "painting" }
    ]
  },
  multistory: {
    name: "3-Story Loft",
    description: "A modern multi-story concrete and steel loft structure with working staircases, balcony handrails, and glass facades for first-person exploration.",
    cubes: [
      { x: -2, y: 0.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 0.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 0.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 0.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 0.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 0.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 0.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 0.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 0.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 0.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 0.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 0.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 0.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 0.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 0.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 0.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 0.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 0.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 0.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 0.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 0.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 0.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 0.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 0.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 0.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 1.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 1.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 2.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 2.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 2.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 2.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 0, y: 1.5, z: -2, material: MATERIALS.GLASS, shape: "door", rotationY: 0 },
      { x: -1, y: 1.5, z: -2, material: MATERIALS.GLASS, shape: "window" },
      { x: 1, y: 1.5, z: -2, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 1.5, z: -1, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 1.5, z: -1, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 1.5, z: 1, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 1.5, z: 1, material: MATERIALS.GLASS, shape: "window" },
      { x: -1, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 0, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 1, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: -1, y: 0.5, z: 0, material: MATERIALS.STEEL, shape: "stair", rotationY: 0 },
      { x: -1, y: 1.5, z: 1, material: MATERIALS.STEEL, shape: "stair", rotationY: 0 },
      { x: -2, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "fence" },
      { x: 0, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 4.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 4.5, z: -2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: 2, y: 4.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 4.5, z: 2, material: MATERIALS.STEEL, shape: "pillar" },
      { x: -2, y: 3.5, z: -1, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 3.5, z: -1, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 3.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 3.5, z: 0, material: MATERIALS.GLASS, shape: "window" },
      { x: -2, y: 3.5, z: 1, material: MATERIALS.GLASS, shape: "window" },
      { x: 2, y: 3.5, z: 1, material: MATERIALS.GLASS, shape: "window" },
      { x: -1, y: 3.5, z: -2, material: MATERIALS.GLASS, shape: "window" },
      { x: -1, y: 3.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 0, y: 3.5, z: -2, material: MATERIALS.GLASS, shape: "window" },
      { x: 0, y: 3.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 1, y: 3.5, z: -2, material: MATERIALS.GLASS, shape: "window" },
      { x: 1, y: 3.5, z: 2, material: MATERIALS.GLASS, shape: "window" },
      { x: 1, y: 2.5, z: 0, material: MATERIALS.STEEL, shape: "stair", rotationY: 2 },
      { x: 1, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "stair", rotationY: 2 },
      { x: -2, y: 4.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 4.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 4.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 4.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 4.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 4.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 4.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 4.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 4.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -1, y: 4.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 4.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 4.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 4.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 4.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 0, y: 4.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 4.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 4.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 4.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 1, y: 4.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 4.5, z: -2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 4.5, z: -1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 4.5, z: 0, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 4.5, z: 1, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: 2, y: 4.5, z: 2, material: MATERIALS.CONCRETE, shape: "slab" },
      { x: -2, y: 5.5, z: -2, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 5.5, z: 2, material: MATERIALS.STEEL, shape: "fence" },
      { x: -1, y: 5.5, z: -2, material: MATERIALS.STEEL, shape: "fence" },
      { x: -1, y: 5.5, z: 2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 0, y: 5.5, z: -2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 0, y: 5.5, z: 2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 1, y: 5.5, z: -2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 1, y: 5.5, z: 2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 2, y: 5.5, z: -2, material: MATERIALS.STEEL, shape: "fence" },
      { x: 2, y: 5.5, z: 2, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 5.5, z: -1, material: MATERIALS.STEEL, shape: "fence" },
      { x: 2, y: 5.5, z: -1, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 5.5, z: 0, material: MATERIALS.STEEL, shape: "fence" },
      { x: 2, y: 5.5, z: 0, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 5.5, z: 1, material: MATERIALS.STEEL, shape: "fence" },
      { x: 2, y: 5.5, z: 1, material: MATERIALS.STEEL, shape: "fence" },
      { x: 1, y: 5.5, z: 0, material: MATERIALS.STEEL, shape: "fence" },
      { x: 0, y: 5.5, z: -1, material: MATERIALS.STEEL, shape: "fence" },
      { x: -2, y: 6.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 6.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 6.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 6.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 6.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 6.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 6.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 6.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 6.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 6.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 6.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 6.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 6.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 6.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 6.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 6.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 6.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 6.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 6.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 6.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 6.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 6.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 6.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 6.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 6.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "table" },
      { x: 1, y: 1.5, z: 1, material: MATERIALS.CARPET, shape: "chair", rotationY: 2 },
      { x: -1, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "table" },
      { x: -1, y: 1.5, z: 1, material: MATERIALS.CARPET, shape: "chair", rotationY: 2 },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "table" },
      { x: 1, y: 3.5, z: 1, material: MATERIALS.CARPET, shape: "chair", rotationY: 2 },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "table" },
      { x: -1, y: 3.5, z: 1, material: MATERIALS.CARPET, shape: "chair", rotationY: 2 },
      { x: 0, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "tv" },
      { x: 1, y: 5.5, z: 0, material: MATERIALS.CARPET, shape: "sofa", rotationY: 3 },
      { x: -1, y: 5.5, z: 0, material: MATERIALS.MARBLE, shape: "table" },
      { x: 0, y: 5.5, z: -1, material: MATERIALS.WOOD, shape: "painting" },
      { x: 0, y: 5.5, z: 1, material: MATERIALS.STEEL, shape: "lamp" }
    ]
  }
};
