const fs = require('fs');

const file = 'd:/My Programs/MediaPipe/Block_Builder/spatial-console/src/simulation/templates.js';
let content = fs.readFileSync(file, 'utf8');

// The modern_house block is all on one line (line 125). 
// Replace from the start of that single-line mess up to (but not including) '  old_house: {'
// Strategy: find the line that starts with 'modern_house: {' and ends before '  old_house: {'
// We'll use a regex that captures the bad line

const modernHouseBlock = `  modern_house: {
    name: "Modern Villa",
    description: "A premium 2-story Modern Villa featuring a marble & tile open-floor plan, steel structural columns, large panoramic glass windows, and interactive doors.",
    cubes: [
      { x: -3, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -3, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -2, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: -1, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 1, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 2, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: -1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 0, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 1, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 2, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 3, y: 0.5, z: 3, material: MATERIALS.MARBLE, shape: "slab" },
      { x: 0, y: 0.5, z: 4, material: MATERIALS.CONCRETE, shape: "stair", rotationY: 0 },
      { x: -3, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 1.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 1.5, z: 3, material: MATERIALS.WOOD, shape: "door", rotationY: 0 },
      { x: 1, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 1.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 1.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 2.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 2.5, z: 3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 2.5, z: 3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 1.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 1.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 1.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -2, y: 2.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: -1, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 0, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 1, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 2, y: 2.5, z: -3, material: MATERIALS.GLASS, shape: "window", rotationY: 0 },
      { x: 3, y: 2.5, z: -3, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: -1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: -1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 0, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 0, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 1, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 1.5, z: 2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: -3, y: 2.5, z: 2, material: MATERIALS.CONCRETE, shape: "cube" },
      { x: 3, y: 1.5, z: -2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: -2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: -1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: -1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 0, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 0, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 1, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 1.5, z: 2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: 3, y: 2.5, z: 2, material: MATERIALS.GLASS, shape: "window", rotationY: 1 },
      { x: -3, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -3, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -2, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: -1, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 0, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 2, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: -1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 0, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 1, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 2, material: MATERIALS.STEEL, shape: "slab" },
      { x: 3, y: 3.5, z: 3, material: MATERIALS.STEEL, shape: "slab" },
      { x: 1, y: 1.5, z: 0, material: MATERIALS.CARPET, shape: "sofa", rotationY: 1 },
      { x: 0, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "table" },
      { x: -1, y: 1.5, z: 0, material: MATERIALS.STEEL, shape: "tv", rotationY: 3 },
      { x: -2, y: 1.5, z: 2, material: MATERIALS.CARPET, shape: "bed", rotationY: 2 },
      { x: 2, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "kitchen_cabinet", rotationY: 0 },
      { x: 1, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "fridge", rotationY: 0 },
      { x: 0, y: 1.5, z: -2, material: MATERIALS.STEEL, shape: "sink", rotationY: 0 },
      { x: -2, y: 1.5, z: -2, material: MATERIALS.MARBLE, shape: "bathtub", rotationY: 1 },
      { x: -1, y: 1.5, z: -2, material: MATERIALS.MARBLE, shape: "toilet", rotationY: 0 },
      { x: 0, y: 1.5, z: 2, material: MATERIALS.STEEL, shape: "lamp" },
      { x: -2.9, y: 1.5, z: 0, material: MATERIALS.WOOD, shape: "painting", rotationY: 3 }
    ]
  },`;

// Replace the bad single-line modern_house block (it contains literal \\n in the line)
const badLineRegex = /^modern_house: \{.*?\n/m;
const newContent = content.replace(badLineRegex, modernHouseBlock + '\n');

if (newContent === content) {
  console.log('Pattern not found — trying alternative replace...');
  // Try stripping surrounding whitespace and matching more loosely
  const altRegex = /\n([ \t]*modern_house: \{\\n[^\n]*)\n/;
  const newContent2 = content.replace(altRegex, '\n' + modernHouseBlock + '\n');
  if (newContent2 !== content) {
    fs.writeFileSync(file, newContent2);
    console.log('Fixed with alternative regex!');
  } else {
    console.log('Still not found. Dumping first 200 chars of line 125 for debug:');
    const lines = content.split('\n');
    console.log(JSON.stringify(lines[124].substring(0, 200)));
  }
} else {
  fs.writeFileSync(file, newContent);
  console.log('Fixed templates.js successfully!');
}
